ignoredBuiltDependencies:
  - '@serialport/bindings-cpp'
  - '@stoprocent/bluetooth-hci-socket'
  - '@stoprocent/noble'

onlyBuiltDependencies:
  - '@abandonware/bluetooth-hci-socket'
  - '@abandonware/noble'
  - esbuild
  - sharp
  - usb
